[[questions]]
question = "Which version of Python is the first with TOML support built-in"
answers = ["3.11"]
options = ["3.9", "3.10", "3.12"]

[[questions]]
question = "What's the name of the list-like data structure in TOML"
answers = ["Array"]
options = ["List", "Sequence", "Set"]

[[questions]]
question ="When was the first known use of the word 'quiz'"
answers = ["1781"]
options = ["1771", "1871", "1881"]

[[questions]]
question = "Which built-in function can get information from the user"
answers = ["input"]
options = ["get", "print", "write"]

[[questions]]
question = "Which keyword do you use to loop over a given list of elements"
answers = ["for"]
options = ["while", "each", "loop"]

[[questions]]
question = "What's the purpose of the built-in zip() function"
answers = ["To iterate over two or more sequences at the same time"]
options = [
    "To combine several strings into one", 
    "To compress several files into one archive", 
    "To get information from the user",
]

[[questions]]
question = "What's the name of Python's sorting algorithm?"
answers = ["Timsort"]
options = ["Quicksort", "Merge sort", "Bubble sort"]

[[questions]]
question= "What does dict.get(key) return if the key isn't found in the dictionary?"
answers = ["None"]
options = ["key", "True", "False"]

[[questions]]
question = "How do you iterate over both indices and elements in an iterable"
answers = "[enumerate(iterable)"]
options = [
    "enumerate(iterable, start=1)", 
    "range(iterable)", 
    "range(iterable, start=1)"
]

[[questions]]
question = "What's the official name of the := operator"
answers =  ["Assignment expression"]
options = ["Named expression", "Walrus operator", "Colon equals operator"]

[[questions]]
question = "What's one effect of calling random.seed(42)"
answers = ["The random numbers are reproducible."]
options = [
    "The random numbers are more random.", 
    "The computer clock is reset.", 
    "The first random number is always 42."
]

[[questions]]
question = "When does __name__ == '__main__' equal True in a Python file"
answers = ["When the file is run as a script"]
options =  [
    "When the file is imported as a module", 
    "When the file has a valid name", 
    "When the file only has one function"
]

[[questions]]
question = "How can you run a Python script named quiz.py"
answers = ["python quiz.py", "python -m quiz.py"]
options = ["python quiz", "python -m quiz.py"]
